#!/usr/bin/env bash
set -eo pipefail

if [ "${EUID}" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

while true; do
    read -p "Are you sure you want to wipe all partitions? " awnser

    case ${awnser} in
        [Yy]*)
            break
            ;;
        [Nn]*)
            exit
            ;;
        *)
            echo "Please answer yes or no!"
            ;;
    esac
done

echo "----> Remove previous VGs"
for VG in $(vgs --noheadings 2>/dev/null | sed -e 's/^[[:space:]]*//' | cut -d" " -f 1); do
    vgremove -y ${VG} 2>/dev/null
done

echo "----> Remove previous PVs"
for PV in $(pvs --noheadings 2>/dev/null | sed -e 's/^[[:space:]]*//' | cut -d" " -f 1); do
    pvremove -y ${PV} 2>/dev/null
done

echo "----> Drop existing partitions"
wipefs -a /dev/sda || true
sfdisk --delete /dev/sda || true

echo "-----> Wait for cleanup"
sleep 3
sync

echo "-----> Mark GPT disks"
echo yes | parted /dev/sda -- mklabel gpt

echo "-----> Create boot partition"
sgdisk -n 0:0:+1G -t 0:ef00 -c 0:boot /dev/sda

echo "-----> Create root partition"
sgdisk -n 0:0:0 -t 0:8300 -c 0:data /dev/sda

echo "-----> Wait for data"
sleep 3
sync

echo "-----> Create data pv"
pvcreate /dev/disk/by-partlabel/data

echo "-----> Create data vg"
vgcreate system /dev/disk/by-partlabel/data

echo "-----> Create swap volume"
lvcreate -y --size 24G --name swap system

echo "-----> Create root volume"
lvcreate -y --size 100G --name root system

echo "-----> Create home volume"
lvcreate -y --size 100G --name home system

echo "-----> Enable swap partition"
mkswap -L swap /dev/system/swap
swapon /dev/system/swap

echo "-----> Create root filesystem"
mkfs.ext4 -L root /dev/system/root

echo "-----> Mount root filesystem"
mount -t ext4 /dev/system/root /mnt

echo "-----> Create home filesystem"
mkfs.ext4 -L home /dev/system/home

echo "-----> Mount home filesystem"
mkdir /mnt/home
mount -t ext4 /dev/system/home /mnt/home

echo "-----> Create boot filesystem"
mkfs.vfat -n boot /dev/disk/by-partlabel/boot

echo "-----> Mount boot filesystem"
mkdir /mnt/boot
mount /dev/disk/by-label/boot /mnt/boot

echo "-----> Wait for filesystems"
sleep 3
sync
