#!/usr/bin/env bash
set -eo pipefail

if [ "${EUID}" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

while true; do
    read -p "Are you sure you want to wipe all partitions? " awnser

    case ${awnser} in
        [Yy]*)
            break
            ;;
        [Nn]*)
            exit
            ;;
        *)
            echo "Please answer yes or no!"
            ;;
    esac
done

echo "----> Remove previous VGs"
for VG in $(vgs --noheadings 2>/dev/null | sed -e 's/^[[:space:]]*//' | cut -d" " -f 1); do
    vgremove -y ${VG} 2>/dev/null
done

echo "----> Remove previous PVs"
for PV in $(pvs --noheadings 2>/dev/null | sed -e 's/^[[:space:]]*//' | cut -d" " -f 1); do
    pvremove -y ${PV} 2>/dev/null
done

echo "----> Drop existing partitions"
sgdisk --zap-all /dev/sda
sgdisk -og /dev/sda
sgdisk --zap-all /dev/sdb
sgdisk -og /dev/sdb

echo "-----> Wait for cleanup"
sleep 3
sync

echo "-----> Create boot partition"
sgdisk -n 0:0:+1G -t 0:ef00 -c 0:boot /dev/sda

echo "-----> Create root partition"
sgdisk -n 0:0:0 -t 0:8300 -c 0:data /dev/sda

echo "-----> Create tank partition"
sgdisk -n 0:0:0 -t 0:8300 -c 0:tank /dev/sdb

echo "-----> Wait for data"
sleep 3
sync

echo "-----> Create data pv"
pvcreate /dev/disk/by-partlabel/data /dev/disk/by-partlabel/tank

echo "-----> Create data vg"
vgcreate system /dev/disk/by-partlabel/data /dev/disk/by-partlabel/tank

echo "-----> Create swap volume"
lvcreate -y --size 24G --name swap system

echo "-----> Create root volume"
lvcreate -y --size 50G --name root system

echo "-----> Create home volume"
lvcreate -y --size 50G --name home system

echo "-----> Enable swap partition"
mkswap -L swap /dev/system/swap
swapon /dev/system/swap

echo "-----> Create root filesystem"
mkfs.ext4 -L root /dev/system/root

echo "-----> Mount root filesystem"
mount -t ext4 /dev/system/root /mnt

echo "-----> Create home filesystem"
mkfs.ext4 -L home /dev/system/home

echo "-----> Mount home filesystem"
mkdir /mnt/home
mount -t ext4 /dev/system/home /mnt/home

echo "-----> Create boot filesystem"
mkfs.vfat -n boot /dev/disk/by-partlabel/boot

echo "-----> Mount boot filesystem"
mkdir /mnt/boot
mount /dev/disk/by-label/boot /mnt/boot

echo "-----> Wait for filesystems"
sleep 3
sync

echo "-----> Create downloads volume"
lvcreate -y --size 200G --name downloads system

echo "-----> Create downloads filesystem"
mkfs.ext4 -L downloads /dev/system/downloads

echo "-----> Mount downloads filesystem"
mkdir -p /mnt/var/lib/downloads
mount -t ext4 /dev/system/downloads /mnt/var/lib/downloads
chown 20000:20000 /mnt/var/lib/downloads

for PARTITION in acme nzbget jellyfin bazarr lidarr prowlarr radarr readarr sonarr hass; do
    echo "-----> Create ${PARTITION} volume"
    lvcreate -y --size 5G --name ${PARTITION} system

    echo "-----> Create ${PARTITION} filesystem"
    mkfs.ext4 -L ${PARTITION} /dev/system/${PARTITION}

    echo "-----> Mount ${PARTITION} filesystem"
    mkdir /mnt/var/lib/${PARTITION}
    mount -t ext4 /dev/system/${PARTITION} /mnt/var/lib/${PARTITION}
done
